services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always

    ports:
      - "6379:6379"

    networks:
      - app-network

    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - cache:/data

    env_file:
      - .env

    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep -q PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redis/redisinsight:2.62
    restart: always
    ports:
      - "5540:5540"

    networks:
      - app-network

    environment:
      - RI_ENCRYPTION_KEY=${RI_ENCRYPTION_KEY}

    volumes:
      - redis-insight:/data

    depends_on:
      redis:
        condition: service_healthy

networks:
  app-network:

volumes:
  redis-insight:
    driver: local
  cache:
    driver: local