services:
  postgres:
    image: postgres:17-alpine3.23
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - app-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    env_file:
      - .env

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

    command: redis-server /usr/local/etc/redis/redis.conf

    networks:
      - app-network

    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - cache:/data

    env_file:
      - .env

    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep -q PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis-insight:
    image: redis/redisinsight:2.62
    restart: unless-stopped
    ports:
      - "5540:5540"

    networks:
      - app-network

    environment:
      - RI_ENCRYPTION_KEY=${RI_ENCRYPTION_KEY}

    volumes:
      - redis-insight:/data

    depends_on:
      redis:
        condition: service_healthy

    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  redis-insight:
    driver: local
  pgdata:
    driver: local
  cache:
    driver: local
  logs:
    driver: local