global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: Java app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'api:8091' ]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: 'go-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'api:8080' ]