server:
  port: 8091

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

#logging
logging:
  level:
    root: DEBUG
    org.hibernate: ERROR
    org.springframework: DEBUG
    com.example.api: WARN
    com.zaxxer.hikari: INFO

management:
  observations:
    annotations:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: '*'