server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:postgresql://postgres/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  config:
    activate:
      on-profile: docker

#logging
logging:
  level:
    root: DEBUG
    org.hibernate: DEBUG
    org.springframework.data.*.*: DEBUG
    org.springframework.cache.*.*: DEBUG
    org.springframework.web.*.*: DEBUG
    org.apache: DEBUG
    com.example.api: DEBUG
    com.zaxxer.hikari: DEBUG

management:
  observations:
    annotations:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: '*'